proxy:
  # the secret token should be changed in your deployment ;)
  secretToken: 4bda3bd04f6ae5ia28368bf7b5514712351fd9cf8edb09ce9b26f73500f8aa54b

singleuser:
  storage:
    type: none

hub:
  db:
    type: foo

scheduling:
  userScheduler:
    enabled: false
